CREATE TABLE IF NOT EXISTS  rssreader_auth.users (
	id  BINARY(16) NOT NULL,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL UNIQUE,
	role_id BINARY(16) NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY (role_id) REFERENCES roles(id)
);
