name: Docker push

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]
env:
  auth-directory: ./auth
jobs:
  push-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: yanncarvalho
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push frontend Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: ${{env.auth-directory}}/
        file: ${{env.auth-directory}}/Dockerfile
        push: true
        tags: |
          yanncarvalho/rssreader-auth:latest
          yanncarvalho/rssreader-auth:${{ github.sha }}
