name: Tests

on: [pull_request, push]

env:
  auth-directory: ./auth
  rss-directory: ./rss
  cloud-gateway-directory: ./cloud-gateway
  config-server-directory: ./config-server
  eureka-server-directory: ./eureka-server
  mongodb-crawler-directory: ./mongodb-crawler

jobs:
  auth-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.auth-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

  rss-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.rss-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

  cloud-gateway-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.cloud-gateway-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

  config-server-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.config-server-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

  eureka-server-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.eureka-server-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean install

  mongodb-crawler-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.mongodb-crawler-directory}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
